import type { Opportunity } from './opportunities';

// First local coverage of the remaining atlas chapters. Every entry links to
// its organizer; consult is deliberate when a current intake is not verified.
const base = {
  resource: false, color: 'black', mark: '', checkedAt: '2026-09-17',
  stages: ['idea', 'prototipo', 'ventas', 'crecimiento'],
  businessTypes: ['startup', 'negocio'], sectors: 'todos',
  cost: 'consultar', costLabel: 'Consultar costo y condiciones con el organizador',
  status: 'consult', mode: 'Por confirmar',
} satisfies Partial<Opportunity>;

export const countryOpportunitiesData: Opportunity[] = [
  {
    ...base, id: 'prendho-incubacion', name: 'Incubación Prendho',
    org: 'Prendho · UTPL', orgType: 'Universidad', category: 'incubacion',
    countryCode: 'EC', geography: 'Ecuador', location: 'Loja · Ecuador',
    description: 'Incubación y aceleración para desarrollar emprendimientos innovadores con el respaldo de la UTPL.',
    benefit: 'Desarrollo del negocio y conexiones', benefitType: 'Acompañamiento',
    url: 'https://prendho.com/sobre-prendho/', needs: ['mentoria', 'tecnologia', 'vender'],
    benefits: ['Servicios de incubación, aceleración y networking.'],
    requirements: ['Consultar la convocatoria que corresponda a tu proyecto y su sector.', 'Confirmar modalidad, dedicación y tarifas de cada programa.'],
    note: 'Ficha de los servicios de Prendho, no una convocatoria abierta. La institución trabaja en TIC, agroindustria, electrónica y bioemprendimiento; cada programa publica sus propios retos y requisitos.',
  },
  {
    ...base, id: 'bolivia-plei', name: 'PLEI · Liderazgo, Emprendimiento e Innovación',
    org: 'Fundación Emprender Futuro', orgType: 'Organización', category: 'capacitacion',
    countryCode: 'BO', geography: 'Bolivia', location: 'Bolivia',
    stages: ['ventas', 'crecimiento'],
    description: 'Formación empresarial en liderazgo, innovación y transformación digital para fortalecer negocios bolivianos.',
    benefit: 'Formación, mentoría y red empresarial', benefitType: 'Formación',
    url: 'https://emprenderfuturo.org/programa-plei/', needs: ['aprender', 'mentoria', 'vender'],
    benefits: ['Entrenamiento empresarial y acceso a mentores y contactos.', 'Posibilidad de becas internacionales para participantes seleccionados.'],
    requirements: ['Consultar criterios para empresarios y emprendedores, costo y calendario de la edición.', 'Las becas internacionales tienen selección adicional.'],
    note: 'No es un fellowship gratuito para todo LATAM. La página presenta el programa y becas selectivas, pero no confirma una inscripción abierta con fecha límite vigente.',
  },
  {
    ...base, id: 'ande-centros-pymes', name: 'Centros Pymes · ANDE',
    org: 'Agencia Nacional de Desarrollo', orgType: 'Estado', category: 'asesoria', resource: true,
    countryCode: 'UY', geography: 'Uruguay', location: 'Centros en todo Uruguay', status: 'ongoing',
    description: 'Red territorial de apoyo a empresas y emprendimientos con asesoramiento y capacitación.',
    benefit: 'Orientación y desarrollo empresarial', benefitType: 'Acompañamiento',
    url: 'https://ande.org.uy/centros-pymes.html', needs: ['mentoria', 'aprender', 'formalizar'],
    benefits: ['Asistencia, consultoría y capacitación.', 'Orientación hacia financiamiento y otros programas.'],
    requirements: ['Contactar el centro correspondiente a tu departamento.', 'Acordar el diagnóstico y las condiciones del servicio.'],
    note: 'La página oficial ofrece un mapa de centros y solicitud de apoyo. La orientación financiera no implica un crédito o subsidio aprobado.',
  },
  {
    ...base, id: 'paraguay-sbdc', name: 'Centros de Desarrollo Empresarial SBDC',
    org: 'Ministerio de Industria y Comercio · Paraguay', orgType: 'Estado', category: 'asesoria', resource: true,
    countryCode: 'PY', geography: 'Paraguay', location: 'Paraguay · consultar centro más cercano',
    status: 'ongoing', cost: 'gratis', costLabel: 'Asesoría y capacitación gratuitas según MIC',
    description: 'Acompañamiento a emprendedores y Mipymes para mejorar gestión, productividad y comercialización.',
    benefit: 'Asesoría empresarial y talleres', benefitType: 'Acompañamiento',
    url: 'https://www.mic.gov.py/centros-sbdc-como-canal-para-el-crecimiento-de-la-microeconomia/',
    sourceUrl: 'https://www.mic.gov.py/los-centros-sbdc-generan-un-impacto-economico-de-mas-g-19-200-millones-en-ventas/',
    needs: ['mentoria', 'formalizar', 'vender'],
    benefits: ['Atención personalizada para mejorar el negocio.', 'Capacitaciones en administración y gestión.'],
    requirements: ['Consultar cobertura territorial, cita y oferta del centro.', 'Ser persona emprendedora o una Mipyme atendida por la red paraguaya.'],
    note: 'Servicio de desarrollo empresarial, no financiamiento directo. Las actividades y los cupos dependen de cada centro; el informe oficial de 2025 confirma atención en San Lorenzo, Encarnación y Alto Paraná.',
  },
  {
    ...base, id: 'tec-catalitec', name: 'Catalitec · TEC Emprende Lab',
    org: 'Tecnológico de Costa Rica', orgType: 'Universidad', category: 'incubacion',
    countryCode: 'CR', geography: 'Costa Rica', location: 'Costa Rica',
    description: 'Incubación de proyectos innovadores y sostenibles con formación y una ruta para solicitar fondos no reembolsables.',
    benefit: 'Incubación y acceso a evaluación para fondos', benefitType: 'Acompañamiento',
    url: 'https://www.tec.ac.cr/proceso-incubacion-tec-emprende-lab', needs: ['capital', 'mentoria', 'aprender'],
    benefits: ['Formación y acompañamiento de TEC Emprende Lab.', 'Banco de proyectos para evaluar acceso a fondos.'],
    requirements: ['Proyecto con contribución al desarrollo de Costa Rica.', 'Revisar si corresponde preincubación o la ruta para equipos con formación previa.'],
    note: 'El formulario es una solicitud de evaluación, no una adjudicación de fondos. La página no fija una convocatoria vigente ni detalla todos los costos: confirmarlos con TEC.',
  },
  {
    ...base, id: 'panama-innovar', name: 'Programa Innovar',
    org: 'Fundación Ciudad del Saber', orgType: 'Organización', category: 'capacitacion', resource: true,
    countryCode: 'PA', geography: 'Panamá', location: 'Virtual · Panamá', mode: 'Virtual',
    stages: ['idea', 'prototipo'], cost: 'gratis', costLabel: 'Programa gratuito',
    description: 'Preemprendimiento autodirigido para identificar una oportunidad y validar una idea de negocio.',
    benefit: '12 horas de formación y ejercicios', benefitType: 'Formación',
    url: 'https://ciudaddelsaber.org/programa-innovar', needs: ['aprender', 'mentoria'],
    benefits: ['Herramientas para validar ideas y construir un modelo de negocio.', 'Certificado sujeto a completar el programa.'],
    requirements: ['Acceso a internet y un dispositivo.', 'Crear un perfil y postular durante una convocatoria.'],
    note: 'Es virtual, pero tiene selección y aperturas periódicas; no acceso inmediato permanente. La página remite a programas de apoyo en Panamá. Confirmar admisión desde otros países.',
  },
  {
    ...base, id: 'guatemala-mineco-sde', name: 'Servicios de Desarrollo Empresarial',
    org: 'MINECO · Guatemala', orgType: 'Estado', category: 'asesoria', resource: true,
    countryCode: 'GT', geography: 'Guatemala', location: 'Guatemala', status: 'ongoing',
    description: 'Apoyo del Viceministerio de Desarrollo de la MIPYME para fortalecer capacidades de negocios y emprendimientos.',
    benefit: 'Orientación para el desarrollo del negocio', benefitType: 'Acompañamiento',
    url: 'https://www.mineco.gob.gt/institucion/viceministerio-de-desarrollo-de-la-mipyme/servicios-de-desarrollo-empresarial',
    needs: ['aprender', 'mentoria', 'formalizar'],
    benefits: ['Ruta institucional de servicios de desarrollo empresarial.'],
    requirements: ['Consultar el servicio y cobertura que correspondan al negocio en Guatemala.', 'Confirmar costo, documentación y calendario con MINECO.'],
    note: 'Es una puerta de entrada a servicios públicos, no una convocatoria de capital ni una garantía de admisión.',
  },
  {
    ...base, id: 'honduras-senprende', name: 'Asistencia empresarial SENPRENDE',
    org: 'SENPRENDE', orgType: 'Estado', category: 'asesoria', resource: true,
    countryCode: 'HN', geography: 'Honduras', location: 'Honduras', status: 'ongoing',
    description: 'Orientación y acompañamiento para emprendimientos, pequeños negocios y empresas de la economía social.',
    benefit: 'Apoyo técnico al emprendimiento', benefitType: 'Acompañamiento',
    url: 'https://senprende.hn/', needs: ['mentoria', 'formalizar', 'vender'],
    benefits: ['Asistencia técnica y acompañamiento para fortalecer el negocio.'],
    requirements: ['Consultar la atención disponible para tu municipio y tipo de negocio.', 'Verificar condiciones y agenda directamente con SENPRENDE.'],
    note: 'Ficha institucional de servicios. No se verificó una convocatoria específica de financiamiento abierta ni una tarifa general para todas las actividades.',
  },
  {
    ...base, id: 'salvador-cdmype', name: 'CDMYPE · Asesoría empresarial',
    org: 'CONAMYPE', orgType: 'Estado', category: 'asesoria', resource: true,
    countryCode: 'SV', geography: 'El Salvador', location: 'El Salvador · red CDMYPE', status: 'ongoing',
    description: 'Centros que acompañan a micro y pequeñas empresas con asesoría, capacitación y asistencia técnica.',
    benefit: 'Asesoría para mejorar la gestión', benefitType: 'Acompañamiento',
    url: 'https://www.conamype.gob.sv/servicios/guia-de-servicios/productos-y-servicios/',
    needs: ['mentoria', 'formalizar', 'aprender'],
    benefits: ['Acompañamiento mediante centros aliados de universidades y organizaciones.'],
    requirements: ['Elegir el centro que atiende tu zona y consultar los requisitos del servicio.'],
    note: 'CONAMYPE publica centros y servicios. Hay asesorías gratuitas, pero no se asume que toda asistencia especializada sea gratuita: revisar la ficha del centro.',
  },
  {
    ...base, id: 'nicaragua-ci-startups', name: 'Incubación de Startups · CI Nicaragua',
    org: 'Centro de Innovación Nicaragua', orgType: 'Estado', category: 'incubacion',
    countryCode: 'NI', geography: 'Nicaragua', location: 'Managua · Nicaragua',
    stages: ['idea', 'prototipo'], businessTypes: ['startup'], sectors: ['tecnologia'],
    description: 'Incubación para equipos multidisciplinarios que desarrollan soluciones de base tecnológica.',
    benefit: 'Desarrollo del producto y del equipo', benefitType: 'Acompañamiento',
    url: 'https://cinicaragua.edu.ni/startups/', needs: ['mentoria', 'tecnologia', 'aprender'],
    benefits: ['Formación técnica y empresarial.', 'Conexiones para proyección del emprendimiento.'],
    requirements: ['Equipo multidisciplinario con una idea tecnológica.', 'Consultar la siguiente convocatoria, modalidad y condiciones.'],
    note: 'El organizador describe convocatorias semestrales, pero no se verificó un cierre vigente. Participar no garantiza inversión ni capital semilla.',
  },
  {
    ...base, id: 'dominicana-mipymes-pucmm', name: 'Centro Mipymes Innovación PUCMM',
    org: 'PUCMM', orgType: 'Universidad', category: 'asesoria', resource: true,
    countryCode: 'DO', geography: 'Rep. Dominicana', location: 'Santo Domingo · República Dominicana', status: 'ongoing',
    description: 'Acompañamiento universitario a Mipymes para fortalecer gestión, innovación y desarrollo empresarial.',
    benefit: 'Asesoría y capacitación empresarial', benefitType: 'Acompañamiento',
    url: 'https://prensa.pucmm.edu.do/academia/2025/07/15/centro-mipymes-innovacion-pucmm-celebra-su-septimo-aniversario/',
    needs: ['mentoria', 'aprender', 'vender'],
    benefits: ['Asesorías para mejorar productos, procesos y operaciones.', 'Programas de capacitación para Mipymes.'],
    requirements: ['Consultar atención, costos y programas disponibles con el centro.', 'Confirmar que el negocio entra en su cobertura.'],
    note: 'La fuente institucional documenta el servicio y sus programas; no es un formulario de inscripción. Consultar la oferta actual antes de desplazarse o postular.',
  },
  {
    ...base, id: 'cuba-taller-emprende', name: 'Taller Emprende',
    org: 'CubaEmprende', orgType: 'Organización', category: 'capacitacion',
    countryCode: 'CU', geography: 'Cuba', location: 'La Habana · Cuba',
    description: 'Formación práctica para quienes quieren iniciar un negocio o mejorar un emprendimiento existente.',
    benefit: 'Herramientas de gestión empresarial', benefitType: 'Formación',
    url: 'https://proyectocubaemprende.org/servicios/', needs: ['aprender', 'vender', 'mentoria'],
    benefits: ['Aprendizaje en modelo de negocio, marketing, ventas y finanzas.'],
    requirements: ['Consultar próxima convocatoria, inscripción, modalidad y costo con CubaEmprende.'],
    note: 'Las aperturas se comunican por los canales oficiales. No se presenta como beca de viaje ni se asume gratuidad. El proyecto también ofrece asesorías empresariales separadas.',
  },
  {
    ...base, id: 'haiti-banj-labs', name: 'Banj Labs',
    org: 'Banj', orgType: 'Organización', category: 'incubacion',
    countryCode: 'HT', geography: 'Haití', location: 'Puerto Príncipe y atención virtual · Haití', mode: 'Híbrido',
    businessTypes: ['startup'],
    description: 'Hub de innovación y acompañamiento para startups y personas emprendedoras de Haití.',
    benefit: 'Mentoría, formación y red emprendedora', benefitType: 'Acompañamiento',
    url: 'https://banj.ht/banj-labs/about', sourceUrl: 'https://banj.ht/banj-labs/methodology',
    needs: ['mentoria', 'tecnologia', 'aprender'],
    benefits: ['Formación y acompañamiento para desarrollar proyectos.', 'Intercambio con otras startups y acceso a recursos del hub.'],
    requirements: ['Confirmar el programa, etapa, idioma y convocatoria adecuados.', 'Verificar costos y disponibilidad de participación virtual o presencial.'],
    note: 'La oferta incluye distintos programas; no se confirma una cohorte abierta ni inversión garantizada. Las fuentes están en francés.',
  },
  {
    ...base, id: 'venezuela-impact-hub', name: 'Programas de Impact Hub Caracas',
    org: 'Impact Hub Caracas', orgType: 'Organización', category: 'incubacion',
    countryCode: 'VE', geography: 'Venezuela', location: 'Caracas · Venezuela',
    description: 'Programas de emprendimiento e innovación desarrollados con empresas y organizaciones aliadas.',
    benefit: 'Acompañamiento y conexiones', benefitType: 'Acompañamiento',
    url: 'https://caracas.impacthub.net/convocatorias/', needs: ['mentoria', 'aprender', 'vender'],
    benefits: ['Acceso a la oferta de programas del hub de Caracas.'],
    requirements: ['Revisar el público, sector, etapa y condiciones de cada convocatoria.'],
    note: 'Es un directorio del organizador; no confirma que todos los programas estén abiertos ni que sean gratuitos. Los requisitos varían por aliado y edición.',
  },
];
