import type { Opportunity } from './opportunities';

// Editorial snapshot: program terms and application windows must be confirmed
// on the linked first-party page before applying. The country is the atlas
// chapter where the provider is based, not a promise of exclusive eligibility.
const common: Pick<
  Opportunity,
  | 'resource' | 'stages' | 'businessTypes' | 'sectors' | 'mode'
  | 'status' | 'cost' | 'costLabel' | 'color' | 'checkedAt'
> = {
  resource: false,
  stages: ['idea', 'prototipo', 'ventas', 'crecimiento'],
  businessTypes: ['startup', 'negocio'],
  sectors: 'todos',
  mode: 'Por confirmar',
  status: 'consult',
  cost: 'consultar',
  costLabel: 'Consultar condiciones oficiales',
  color: 'black',
  checkedAt: '2026-09-16',
};
const place = {
  MX: { countryCode: 'MX', geography: 'México', location: 'México' },
  CO: { countryCode: 'CO', geography: 'Colombia', location: 'Colombia' },
  CL: { countryCode: 'CL', geography: 'Chile', location: 'Chile' },
  AR: { countryCode: 'AR', geography: 'Argentina', location: 'Argentina' },
  BR: { countryCode: 'BR', geography: 'Brasil', location: 'Brasil' },
} as const;

export const latamOpportunities: Opportunity[] = [
  {
    ...common, ...place.MX,
    id: 'ife-accelerator', name: 'IFE Accelerator', org: 'IFE · Tecnológico de Monterrey', orgType: 'Universidad',
    category: 'incubacion', mark: 'IFE', matchScope: 'Latinoamérica',
    description: 'Aceleración EdTech para startups mexicanas e internacionales que buscan expandirse en México y LATAM.',
    benefit: 'Mentoría e inmersión en México', benefitType: 'Acompañamiento',
    url: 'https://edtech.tec.mx/en/ife-accelerator-en',
    sourceUrl: 'https://edtech.tec.mx/sites/g/files/vgjovo1926/files/%5BIFE%20Accelerator%2026%5D%20Bases%20EN.pdf',
    stages: ['prototipo', 'ventas', 'crecimiento'], businessTypes: ['startup'], sectors: ['tecnologia'],
    needs: ['mentoria', 'vender'], mode: 'Híbrido', location: 'En línea, Ciudad de México y Monterrey',
    status: 'closed', cost: 'condicionado', costLabel: 'Sin equity; comisión comercial y gastos de viaje', checkedAt: '2026-09-17',
    benefits: [
      'Mentoría especializada, conexiones comerciales y posibles pilotos educativos.',
      'Inmersión, eventos y presentación ante inversionistas; no garantiza inversión.',
      'Alojamiento, alimentación y vuelos a Monterrey según cobertura oficial para una persona del equipo.',
    ],
    requirements: [
      'Solución EdTech con producto mínimo viable o más avanzada; revisar las verticales prioritarias.',
      'Inglés, español y disponibilidad para las actividades presenciales.',
      'Documentación para viajar y seguro médico internacional; vuelo a CDMX y otros gastos excluidos a cargo del participante.',
      'Las bases exigen 5% de los ingresos netos de contratos originados por el programa durante 12 meses; no de toda la facturación.',
    ],
    note: 'Edición 2026 cerrada. La web indica 26 de julio; el PDF, 19 de julio. También difieren los calendarios de inicio e inmersión: confirmar con IFE. No se verificó una nueva convocatoria. Equity-free no significa totalmente gratuito.',
  },
  {
    ...common, ...place.MX,
    id: 'incmty-accelerator', name: 'incMTY Accelerator', org: 'incMTY · Tecnológico de Monterrey', orgType: 'Universidad',
    category: 'incubacion', mark: 'i',
    description: 'Aceleración para startups con mentoría, comunidad y conexiones del ecosistema de Monterrey.',
    benefit: 'Aceleración y mentoría', benefitType: 'Acompañamiento',
    url: 'https://incmty.com/es/inc-accelerator',
    stages: ['prototipo', 'ventas', 'crecimiento'], businessTypes: ['startup'], needs: ['mentoria', 'vender'],
    benefits: ['Mentoría y acompañamiento para crecimiento.', 'Conexiones con empresas y el ecosistema de innovación.'],
    requirements: ['Revisar el perfil de startup y las bases de la edición vigente.', 'Confirmar fechas y si la convocatoria acepta equipos fuera de México.'],
    note: 'La aceleración no implica una inversión garantizada. Revisa la edición y sus condiciones en incMTY.',
  },
  {
    ...common, ...place.MX,
    id: 'startup-mexico-aceleracion', name: 'Aceleración SUM', org: 'Startup México', orgType: 'Organización',
    category: 'incubacion', mark: 'SUM',
    description: 'Aceleración enfocada en crecimiento, estrategia y expansión de negocios mexicanos.',
    benefit: 'Mentoría y plan de crecimiento', benefitType: 'Acompañamiento',
    url: 'https://startupmexico.com/aceleracion/',
    stages: ['ventas', 'crecimiento'], needs: ['mentoria', 'vender'],
    benefits: ['Plan de crecimiento y asesoría especializada.', 'Acceso a la comunidad de Startup México.'],
    requirements: ['La página publica criterios de operación y ventas mínimas.', 'Consultar fechas, admisión y costo de la edición vigente.'],
    note: 'No se presenta como inversión o financiamiento garantizado; revisa los criterios de facturación en el sitio oficial.',
  },
  {
    ...common, ...place.MX,
    id: 'nafin-fundamentos', name: 'Fundamentos de negocio', org: 'Nacional Financiera', orgType: 'Estado',
    category: 'capacitacion', resource: true, mark: 'N',
    description: 'Material de Nacional Financiera para aprender conceptos básicos de administración y emprendimiento.',
    benefit: 'Recursos formativos', benefitType: 'Formación',
    url: 'https://www.nafin.gob.mx/portalnf/content/herramientas-negocio/fundamentos_negocio.html',
    status: 'ongoing', mode: 'Virtual', cost: 'gratis', costLabel: 'Consulta gratuita', needs: ['aprender', 'formalizar'],
    benefits: ['Guías y contenidos de fundamentos empresariales.', 'Acceso en línea desde el portal oficial.'],
    requirements: ['Confirmar si cada recurso requiere registro.', 'Los contenidos no constituyen aprobación de crédito.'],
    note: 'Recurso formativo; se distingue de los productos financieros de Nafin.',
  },
  {
    ...common, ...place.MX,
    id: '500-latam', name: '500 Global · LatAm', org: '500 Global', orgType: 'Empresa',
    matchScope: 'Latinoamérica',
    category: 'inversion', mark: '500',
    description: 'Programa de inversión y crecimiento para startups tecnológicas de Latinoamérica.',
    benefit: 'Capital a cambio de participación', benefitType: 'Inversión por participación',
    url: 'https://500.co/latam', sourceUrl: 'https://latam.aplica.500.co/',
    stages: ['prototipo', 'ventas', 'crecimiento'], businessTypes: ['startup'], sectors: ['tecnologia'], needs: ['capital', 'mentoria'],
    status: 'closed', cost: 'condicionado', costLabel: 'Condiciones de inversión sujetas a selección',
    benefits: ['Inversión para compañías seleccionadas.', 'Acompañamiento y red internacional.'],
    requirements: ['Startup tecnológica con potencial de escala.', 'Consultar términos de participación y el próximo proceso de selección.'],
    note: 'La cohorte publicada de 2026 cerró el 31 de julio. Se ubica en México como referencia del mapa, pero el programa se dirige a Latinoamérica.',
  },
  {
    ...common, ...place.MX,
    id: 'latitud-fellowship', name: 'Latitud Fellowship', org: 'Latitud', orgType: 'Empresa',
    matchScope: 'Latinoamérica',
    category: 'inversion', mark: 'L',
    description: 'Programa remoto para fundadores latinoamericanos en etapa inicial, con inversión y comunidad.',
    benefit: 'Inversión mediante SAFE', benefitType: 'Inversión por participación',
    url: 'https://www.fellowship.latitud.com/',
    stages: ['idea', 'prototipo'], businessTypes: ['startup'], needs: ['capital', 'mentoria'],
    status: 'closed', mode: 'Virtual', cost: 'condicionado', costLabel: 'USD 62,500 por 2.5% · términos publicados',
    benefits: ['Inversión bajo las condiciones publicadas para equipos seleccionados.', 'Comunidad y sesiones con otros fundadores.'],
    requirements: ['Revisar perfil de fundador, fechas y documentos de la próxima cohorte.', 'Leer el SAFE y confirmar la dilución antes de aplicar.'],
    note: 'La postulación publicada para 2026 cerró en febrero. El programa es regional; México es su capítulo de referencia en el mapa.',
  },
  {
    ...common, ...place.CO,
    id: 'innpulsa-convocatorias', name: 'Convocatorias iNNpulsa', org: 'iNNpulsa Colombia', orgType: 'Estado',
    category: 'asesoria', resource: true, mark: 'i',
    description: 'Portal oficial para consultar convocatorias, programas y apoyos al emprendimiento colombiano.',
    benefit: 'Directorio de convocatorias', benefitType: 'Directorio',
    url: 'https://convocatorias.innpulsacolombia.com/',
    status: 'ongoing', mode: 'Virtual', cost: 'gratis', costLabel: 'Consulta gratuita', needs: ['aprender', 'capital', 'mentoria'],
    benefits: ['Convocatorias y fichas de programas en un mismo lugar.', 'Enlaces a las condiciones de cada iniciativa.'],
    requirements: ['Cada convocatoria tiene público objetivo y fechas diferentes.', 'Verificar bases y vigencia de la ficha elegida.'],
    note: 'El directorio está disponible; eso no significa que todas sus convocatorias estén abiertas.',
  },
  {
    ...common, ...place.CO,
    id: 'fondo-emprender-sena', name: 'Fondo Emprender', org: 'SENA', orgType: 'Estado',
    category: 'financiamiento', mark: 'S',
    description: 'Capital semilla para crear o fortalecer empresas mediante convocatorias del SENA.',
    benefit: 'Capital semilla sujeto a condiciones', benefitType: 'Capital semilla condonable',
    url: 'https://www.fondoemprender.com/SitePages/Home.aspx',
    needs: ['capital', 'formalizar'], cost: 'condicionado', costLabel: 'Condonación sujeta a cumplimiento',
    benefits: ['Capital semilla según cada convocatoria.', 'Ruta de acompañamiento para formular y ejecutar el plan.'],
    requirements: ['Cumplir el perfil de beneficiario y las bases de una convocatoria activa.', 'La condonación depende de las metas y condiciones establecidas.'],
    note: 'No es inversión de venture capital ni dinero sin condiciones. Consulta convocatorias y reglamento oficiales.',
  },
  {
    ...common, ...place.CO,
    id: 'rockstart-latam', name: 'Rockstart LatAm', org: 'Rockstart', orgType: 'Empresa',
    matchScope: 'Latinoamérica',
    category: 'inversion', mark: 'R',
    description: 'Aceleradora e inversionista para startups de Latinoamérica, con operación regional desde Colombia.',
    benefit: 'Inversión y aceleración', benefitType: 'Inversión por participación',
    url: 'https://rockstart.com/latam/', sourceUrl: 'https://rockstart.com/latam/faq/',
    stages: ['prototipo', 'ventas', 'crecimiento'], businessTypes: ['startup'], needs: ['capital', 'mentoria'],
    cost: 'condicionado', costLabel: 'Participación a confirmar con el fondo',
    benefits: ['Posible inversión para compañías seleccionadas.', 'Mentores, red y apoyo para expansión.'],
    requirements: ['Revisar tesis de inversión, países admitidos y etapa.', 'Confirmar términos de equity y próxima convocatoria.'],
    note: 'Se muestra en Colombia por su presencia en Bogotá, pero su alcance es regional. No se presenta como convocatoria abierta sin una fecha verificada.',
  },
  {
    ...common, ...place.CL,
    id: 'startup-chile-ignite', name: 'Start-Up Chile Ignite', org: 'CORFO · Start-Up Chile', orgType: 'Estado',
    category: 'financiamiento', mark: 'SUP',
    description: 'Aceleración y apoyo económico sin cesión de participación para startups en validación.',
    benefit: 'Capital y aceleración equity-free', benefitType: 'Subvención',
    url: 'https://startupchile.org/postula/ignite/',
    stages: ['prototipo', 'ventas'], businessTypes: ['startup'], needs: ['capital', 'mentoria'],
    cost: 'condicionado', costLabel: 'Aporte y requisitos según convocatoria',
    benefits: ['Aceleración y acceso al ecosistema de Start-Up Chile.', 'Apoyo financiero sin entrega de equity, sujeto a bases.'],
    requirements: ['Producto funcional y validación inicial según las bases.', 'Revisar elegibilidad, fechas y obligaciones de estancia en Chile.'],
    note: 'La página indica próxima apertura; confirma montos y calendario en la edición vigente.',
  },
  {
    ...common, ...place.CL,
    id: 'sercotec-capital-semilla', name: 'Capital Semilla Emprende', org: 'Sercotec', orgType: 'Estado',
    category: 'financiamiento', mark: 'S',
    description: 'Fondo para iniciar un negocio y apoyar su formalización, con convocatorias por región.',
    benefit: 'Subsidio concursable', benefitType: 'Subvención',
    url: 'https://www.sercotec.cl/programas-y-servicios-digitalizados/',
    businessTypes: ['negocio'], needs: ['capital', 'formalizar'], cost: 'condicionado', costLabel: 'Aporte propio y condiciones por región',
    benefits: ['Financiamiento de inversión y acciones para poner en marcha un negocio.', 'Apoyo en formalización según la convocatoria.'],
    requirements: ['Revisar bases de la región correspondiente.', 'Confirmar requisitos de inicio de actividades y aporte propio.'],
    note: 'No existe una fecha única nacional: las aperturas y montos cambian por región.',
  },
  {
    ...common, ...place.CL,
    id: 'platanus-programa', name: 'Platanus', org: 'Platanus', orgType: 'Empresa',
    category: 'inversion', mark: 'P',
    description: 'Programa de inversión y comunidad para startups tecnológicas de habla hispana.',
    benefit: 'USD 200,000 por 7% · términos publicados', benefitType: 'Inversión por participación',
    url: 'https://platan.us/programa',
    stages: ['idea', 'prototipo', 'ventas'], businessTypes: ['startup'], sectors: ['tecnologia'], needs: ['capital', 'mentoria'],
    status: 'closed', cost: 'condicionado', costLabel: 'SAFE posdinero · 7% publicado',
    benefits: ['Inversión y tres meses de programa para equipos seleccionados.', 'Comunidad de fundadores y apoyo para levantar capital.'],
    requirements: ['Equipo fundador técnico y dedicación de tiempo completo según sus criterios.', 'Confirmar próxima cohorte y revisar el SAFE antes de decidir.'],
    note: 'La convocatoria publicada cerró el 30 de abril de 2026. Está en Chile como referencia del mapa, pero acepta equipos de otros países hispanohablantes.',
  },
  {
    ...common, ...place.AR,
    id: 'endeavor-argentina-premio', name: 'Premio a la Innovación con Impacto', org: 'Endeavor Argentina · FBN', orgType: 'Organización',
    category: 'incubacion', mark: 'E',
    description: 'Reconocimiento con mentoría y premio para startups argentinas que generan impacto.',
    benefit: 'Premio y acompañamiento', benefitType: 'Acompañamiento',
    url: 'https://www.endeavor.org.ar/programas/fbn-endeavor/',
    stages: ['prototipo', 'ventas', 'crecimiento'], businessTypes: ['startup'], needs: ['mentoria', 'capital'],
    status: 'open', closesAt: '2026-09-30T23:59:59-03:00', cost: 'gratis', costLabel: 'Postulación sin costo publicado',
    benefits: ['Mentoría y visibilidad para proyectos seleccionados.', 'Premio económico según las bases de la edición 2026.'],
    requirements: ['Verificar sectores y criterios de impacto en las bases.', 'Postular antes del cierre publicado: 30 de septiembre de 2026.'],
    note: 'Convocatoria 2026 abierta al momento de la revisión. La fuente publica el día de cierre, no la hora; la base de datos toma el final del día local solo para no seguir marcándola abierta después. Confirma la hora exacta en la fuente.',
  },
  {
    ...common, ...place.AR,
    id: 'empretec-taller', name: 'Taller Empretec', org: 'Fundación Empretec Argentina', orgType: 'Organización',
    category: 'capacitacion', resource: true, mark: 'E',
    description: 'Formación en habilidades y comportamientos emprendedores a través de talleres.',
    benefit: 'Taller de formación', benefitType: 'Formación',
    url: 'https://www.empretec.org.ar/taller-empretec',
    needs: ['aprender', 'mentoria'], cost: 'consultar', costLabel: 'Consultar fecha y costo de cada taller',
    benefits: ['Aprendizaje práctico y ejercicios de desarrollo emprendedor.', 'Red de participantes y facilitadores.'],
    requirements: ['Revisar sede, modalidad, calendario y precio de la edición.', 'Puede requerir inscripción y selección previa.'],
    note: 'Se muestra como recurso permanente; cada taller tiene su propio calendario.',
  },
  {
    ...common, ...place.AR,
    id: 'emprendimiento-argentino', name: 'Emprendimiento Argentino', org: 'Gobierno de Argentina', orgType: 'Estado',
    category: 'mercados', mark: 'AR',
    description: 'Iniciativa federal para dar visibilidad y conexiones a emprendimientos argentinos.',
    benefit: 'Visibilidad y conexiones', benefitType: 'Acceso comercial',
    url: 'https://www.argentina.gob.ar/node/503862',
    status: 'closed', needs: ['vender', 'mentoria'],
    benefits: ['Presentación de proyectos y conexiones del ecosistema.', 'Reconocimiento para emprendimientos destacados.'],
    requirements: ['Verificar las bases de futuras ediciones.', 'Confirmar criterios de postulación y representación provincial.'],
    note: 'La postulación 2026 cerró el 31 de julio; se conserva para conocer la iniciativa y futuras ediciones.',
  },
  {
    ...common, ...place.BR,
    id: 'sebrae-startups', name: 'Sebrae Startups', org: 'Sebrae', orgType: 'Organización',
    category: 'asesoria', resource: true, mark: 'S',
    description: 'Portal de programas, contenidos y oportunidades para startups de Brasil.',
    benefit: 'Directorio de programas', benefitType: 'Directorio',
    url: 'https://programas.sebraestartups.com.br/',
    status: 'ongoing', mode: 'Virtual', cost: 'gratis', costLabel: 'Consulta gratuita', businessTypes: ['startup'], needs: ['aprender', 'mentoria', 'capital'],
    benefits: ['Exploración de programas del ecosistema Sebrae.', 'Información sobre apoyos y próximas convocatorias.'],
    requirements: ['Cada programa tiene su propio perfil y calendario.', 'Confirmar requisitos de empresa, residencia y etapa.'],
    note: 'El portal está disponible; sus programas individuales pueden no estar abiertos.',
  },
  {
    ...common, ...place.BR,
    id: 'bndes-garagem', name: 'BNDES Garagem', org: 'BNDES', orgType: 'Estado',
    category: 'incubacion', mark: 'B',
    description: 'Programa de aceleración para negocios innovadores de impacto en Brasil.',
    benefit: 'Aceleración y conexiones', benefitType: 'Acompañamiento',
    url: 'https://garagem.bndes.gov.br/sobre/',
    stages: ['prototipo', 'ventas', 'crecimiento'], needs: ['mentoria', 'vender'],
    benefits: ['Mentoría y metodología de aceleración.', 'Acceso a redes de aliados y posibles oportunidades de negocio.'],
    requirements: ['Consultar convocatoria, tema y etapas de selección del ciclo vigente.', 'Los premios o inversiones no están garantizados para todos los participantes.'],
    note: 'El programa opera por ciclos; la existencia del sitio no significa postulación abierta.',
  },
  {
    ...common, ...place.BR,
    id: 'brasil-mais-produtivo', name: 'Brasil Mais Produtivo', org: 'MDIC · Gobierno de Brasil', orgType: 'Estado',
    category: 'asesoria', mark: 'BR',
    description: 'Apoyo para que micro, pequeñas y medianas empresas mejoren productividad y adopten tecnología.',
    benefit: 'Orientación y transformación productiva', benefitType: 'Acompañamiento',
    url: 'https://brasilmaisprodutivo.mdic.gov.br/',
    businessTypes: ['negocio'], needs: ['aprender', 'tecnologia'],
    benefits: ['Diagnóstico y servicios de productividad según la modalidad.', 'Orientación para incorporar tecnología y mejores procesos.'],
    requirements: ['Verificar tamaño de empresa, sector y localidad admitidos.', 'Consultar el modo de inscripción y prestaciones disponibles.'],
    note: 'Las modalidades y cupos pueden cambiar; confirmar condiciones en el portal del Gobierno de Brasil.',
  },
];
