import type { Opportunity } from './opportunities';

// Cross-border opportunities belong to a separate chapter, not to the
// country where an organizer happens to have an office.
export const regionalOpportunities: Opportunity[] = [
  {
    id: 'puentes-antigravity',
    name: 'Puentes Fellowship',
    org: 'Antigravity Capital',
    orgType: 'Empresa',
    category: 'fellowships',
    resource: false,
    description: 'Una semana en San Francisco para ingenieros de Latinoamérica: conversaciones con founders y conexiones con startups que contratan talento internacional.',
    benefit: 'Alojamiento y la mayoría de comidas durante la semana',
    benefitType: 'Acompañamiento',
    cost: 'condicionado',
    costLabel: 'Sin cuota publicada; vuelos y traslados por tu cuenta',
    mark: 'P',
    color: 'black',
    url: 'https://puentes.antigravity.capital/',
    stages: ['idea', 'prototipo', 'ventas', 'crecimiento'],
    businessTypes: ['startup'],
    sectors: ['tecnologia'],
    needs: ['mentoria', 'aprender'],
    geography: 'Latinoamérica',
    location: 'San Francisco, Estados Unidos',
    mode: 'Presencial',
    status: 'closed',
    closesAt: '2026-09-10T20:00:00-07:00',
    benefits: ['Estancia y la mayoría de las comidas cubiertas durante Puentes Week.', 'Encuentros con fundadores de startups y potenciales entrevistas.'],
    requirements: ['Perfil individual de ingeniería en Latinoamérica, con proyecto técnico que puedas explicar.', 'Cubrir vuelo, transporte local y comidas fuera de la casa; confirmar requisitos de entrada a EE. UU.'],
    note: 'La cohorte del 18 al 26 de octubre de 2026 cerró postulaciones el 10 de septiembre a las 8 p. m. hora del Pacífico. Es una experiencia de talento, no una aceleradora ni una inversión. No garantiza empleo ni autorización de trabajo: cualquier empleo posterior requiere un permiso independiente. La organización menciona cohortes en mayo y octubre; espera el anuncio de la siguiente antes de postular.',
    checkedAt: '2026-09-17',
    matchEligible: false,
  },
  {
    id: 'ylai-fellowship',
    name: 'YLAI Fellowship',
    org: 'U.S. Department of State · IREX',
    orgType: 'Estado',
    category: 'fellowships',
    resource: false,
    description: 'Intercambio de seis semanas para emprendedores de América Latina y el Caribe, con experiencia en una organización de Estados Unidos.',
    benefit: 'Intercambio profesional con apoyo de viaje y estancia',
    benefitType: 'Acompañamiento',
    cost: 'gratis',
    costLabel: 'Sin costo de postulación; cobertura según la cohorte',
    mark: 'Y',
    color: 'black',
    url: 'https://exchanges.state.gov/non-us/program/ylai-program',
    stages: ['ventas', 'crecimiento'],
    businessTypes: ['startup', 'negocio'],
    sectors: 'todos',
    needs: ['mentoria', 'aprender', 'vender'],
    geography: 'Latinoamérica',
    location: 'Estados Unidos · países participantes de América Latina y el Caribe',
    mode: 'Presencial',
    status: 'consult',
    benefits: ['Experiencia profesional y red de contactos en Estados Unidos.', 'La documentación de IREX describe pasajes de ida y vuelta, alojamiento, estipendio y apoyo para la visa J-1; verificar condiciones de la próxima cohorte.'],
    requirements: ['Tener entre 25 y 35 años al empezar y ciudadanía y residencia en un país participante; Perú, México, Colombia, Chile, Argentina y Brasil figuran entre ellos.', 'Haber desarrollado tu negocio o emprendimiento social durante al menos dos años, dominar inglés y poder recibir visa J-1.'],
    note: 'La cohorte 2026 ya comenzó y no se verificó una nueva fecha de apertura. El enlace principal lleva a la ficha vigente del Departamento de Estado. La descripción de cobertura de IREX corresponde a información histórica y debe reconfirmarse para la siguiente edición; el sitio de IREX conserva llamadas antiguas a postular.',
    checkedAt: '2026-09-17',
  },
  {
    id: 'makers-fellowship',
    name: 'Makers Fellowship',
    org: 'Makers',
    orgType: 'Organización',
    category: 'fellowships',
    resource: false,
    description: 'Comunidad y programa remoto para jóvenes de LATAM que quieren construir productos de IA, negocios o proyectos de software.',
    benefit: 'Mentoría y formación remota',
    benefitType: 'Formación',
    cost: 'gratis',
    costLabel: '100 % gratuito según el organizador',
    mark: 'M',
    color: 'black',
    url: 'https://www.makers.ngo/',
    stages: ['idea', 'prototipo'],
    businessTypes: ['startup'],
    sectors: ['tecnologia'],
    needs: ['mentoria', 'aprender', 'tecnologia'],
    geography: 'Latinoamérica',
    location: 'Remoto · Latinoamérica',
    mode: 'Virtual',
    status: 'open',
    closesAt: '2026-09-20T23:59:59-05:00',
    benefits: ['Tracks de AI Business y Coding, comunidad y mentores.', 'Participación remota, sin viaje a Estados Unidos.'],
    requirements: ['Tener entre 18 y 25 años; selección con conversación en inglés y ejercicio práctico.', 'Verificar el track y la fecha de cierre en la página oficial.'],
    note: 'La página anuncia cierre el 20 de septiembre de 2026, sin publicar hora. La base de datos utiliza el final de ese día únicamente para dejar de mostrarla abierta después; comprueba el horario real antes de aplicar. Es una alternativa remota, no una beca de viaje a EE. UU.',
    checkedAt: '2026-09-17',
  },
];
